import { Footer } from '@/components/footer/Footer';
import type { Metadata } from 'next';
import { shipporiAntique, shipporiMincho } from '../font';
import '../globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`base ${shipporiMincho.variable} ${shipporiAntique.variable} antialiased`}
      >
        {/* <Header /> */}
        <div className='bg-white '>
          {/* <Header /> */}
          {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}
