import { Footer } from '@/components/footer/Footer';
import { Header } from '@/components/header/Header';
import type { Metadata } from 'next';
import { shipporiAntique, shipporiMincho } from '../font';
import '../globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`base ${shipporiMincho.variable} ${shipporiAntique.variable} antialiased h-screen flex flex-col`}
      >
        <Header />
        <div className='flex-1 max-w-sm px-4 pt-8 mx-auto bg-white'>
          {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}
